### ISSUE TITLE
Destination disappearing

### ISSUE THREAD

**Issue by denro2** [jfoot/Bus-Departure-Board#27] opened 2021-10-14 20:48 UTC
**Describe the bug**
When using the device to show National Rail services the destinations dissapear from the screen once the calling at animations have run

**To Reproduce**
Steps to reproduce the behaviour:
Upon startup of Raspberry Pi
Have tried several different stations with the same behaviour seen

**Expected behaviour**
Destination name should remain visible for each train service

**Screenshots or Error Trace**

**Program information:**
 - Pi Type - Pi Zero WH
 - Program - NationalRail.py
 - Version - 2.6.NR

**Additional context**
Add any other context about the problem here
[Tra.zip](https://github.com/jfoot/Bus-Departure-Board/files/7349276/Tra.zip)
.

**Comment by jfoot** [comment] 2021-10-15 12:17
Hi @denro2 thanks for the bug report, I'll have a look into this soon, I'll need to reset up my dev environment on my new device, so please give me a bit of time and I'll get back to you soon :)

**Comment by jfoot** [comment] 2021-12-28 00:31
Hi @denro2, I'm very sorry it took so long for me to look into this for you and thank you for your patience! This turned out to be a rather strange issue, on my emulator (and where I do all my development) I couldn't reproduce, then even when using real hardware I could only reproduce some of the time. In the end it looks like I was simply measuring the wrong thing and as such drawing the destination off screen; so a relatively simple fix, I'm not sure why it wasn't reproducible on my emulator though.

I've already pushed the edits onto Master, so you're display should automatically update if left on for 24hrs, or you can force it to update by doing a git pull. Although, I'm going to do some more in-depth testing tomorrow before officially marking this issue as closed.  

Once again, I'm really sorry about the time it took, been very busy with uni work these past few months :(

**Comment by jfoot** [comment] 2021-12-28 14:12
I've now tested this and I am confident it seems to have resolved the issue, so shall be closing the issue. But please do let me know if you experience any other issues. Thanks, Jonathan.

**Closed by jfoot** 2021-12-28 14:12 UTC
Labels: bug

**Comment by denro2** [comment] 2021-12-28 14:40
Thank you!
