### ISSUE TITLE
AttributeError: 'ImageDraw' object has no attribute 'textsize'

### ISSUE THREAD

**Issue by walderston** [jfoot/Bus-Departure-Board#31] opened 2023-07-08 10:45 UTC
Following the steps from the guide on https://departureboard.jonathanfoot.com/SoftwareDownload.html. 

Running ```sudo -H pip3 install -U setuptools luma.oled luma.emulator inflect nre-darwin-py``` it throws an error 

```
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /tmp/tmp4etdzu6q_in_process.py prepare_metadata_for_build_wheel /tmp/tmpxj0fhdwm
         cwd: /tmp/pip-install-0eb2p37u/pydantic-core_1834ada08082489c8b5abc5d7143bf23
    Complete output (6 lines):

    Cargo, the Rust package manager, is not installed or is not on PATH.
    This package requires Rust and Cargo to compile extensions. Install it through
    the system's package manager or via https://rustup.rs/

    Checking for Rust toolchain....
    ----------------------------------------
```
when I continue and get to the ```python3 DemoPy3.py``` it then throws another error 

```
Traceback (most recent call last):
  File "/home/pi/Bus-Departure-Board/DemoPy3.py", line 626, in <module>
    board = boardFixed(image_composition,Args.Delay,device)
  File "/home/pi/Bus-Departure-Board/DemoPy3.py", line 516, in __init__
    self.setInitalCards()
  File "/home/pi/Bus-Departure-Board/DemoPy3.py", line 527, in setInitalCards
    self.top = ScrollTime(image_composition, len(self.Services) >= 1 and self.Services[0] or LiveTimeStud(),LiveTimeStud(), self.scroll_delay, self.synchroniser, device, 0, self)
  File "/home/pi/Bus-Departure-Board/DemoPy3.py", line 292, in __init__
    self.generateCard(service)
  File "/home/pi/Bus-Departure-Board/DemoPy3.py", line 314, in generateCard
    displayTimeTemp = TextImage(device, service.DisplayTime)
  File "/home/pi/Bus-Departure-Board/DemoPy3.py", line 178, in __init__
    self.width = 5 + draw.textsize(text, BasicFont)[0]
AttributeError: 'ImageDraw' object has no attribute 'textsize'
```

**Comment by jfoot** [comment] 2023-07-08 12:04
@walderston thanks for the bug report, I know the cause of this, its due to Pillow (version 10) deprecating support for the "textsize" function. I've been meaning to do some work on this project for a while, just been struggling to find the time. I'll have a look into and fix this bug at some point this week.

**Comment by walderston** [comment] 2023-07-11 16:19
@jfoot thanks 👍 
worried I was doing something wrong

**Comment by jfoot** [comment] 2023-07-16 21:31
Hi again @walderston just to give you an update, I've started working on creating a fix for this and its working on my emulator, but not on my actual physical Pi. I'm going to continue looking into this over the next few days when time allows.

Although, the fix might work for you, if you want to give it a try my current code is on the "dev" branch, so switch to that one instead for now :)  Will  update again soon.

**Comment by Tom-AW** [comment] 2023-09-22 20:46
Current quick fix on my end seems to be, go into main directory and run this `python3 -m pip install --upgrade pillow==9.5.0` to force pillow back to the old version that supports textsize.

**Comment by amjohnno** [comment] 2023-10-06 05:28
@Tom-AW, your quick fix worked for me. Many thanks.

**Closed** 2023-10-08 22:50 UTC
Labels: bug

**Comment by jfoot** [comment] 2023-10-08 23:00
Hi all, really sorry for such a delyed response to this, I've now updated all of the programs so that they can run on the latest versions of Pillow and all the other dependencies. I've also updated the instructions on the website to include a slightly simplier first time set up process. If you've already downgraded to an older version of Pillow and repull the repository I've moved the original scripts into a new `/legacy` folder.

Ideally, I should just create a script that downloads specific versions of all of the dependencies to make sure this never happens again. This project was started way back in 2019 and was one of the first big projects in Python I'd ever done. The code as you can all see is far from ideal and needs a pretty major refactoring/re-write. Hopefully one day, not too far away I'll get around to it and simplify/improve the whole installation and update/upgrade process. 

But until then, thanks everyone for your intrest in the project and thanks @Tom-AW  for your workaround 😊
